[tool.pylint.'MASTER']
max-line-length = 200
ignore-imports = true
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "too-many-instance-attributes",
    "too-many-branches",
    "too-few-public-methods",
    "oo-many-public-methods",
    "too-many-arguments",
    "duplicate-code",
    "c-extension-no-member",
    "fixme",
    "no-member",
    "wrong-import-order",
    "ungrouped-imports",
    "no-else-return",
    "too-many-public-methods",
    "too-many-statements",
    "broad-except",
]

[tool.black]
line-length = 200

[tool.isort]
profile = "black"
force_sort_within_sections = true
combine_as_imports = true
line_length = 200
known_first_party = ["camera", "configuration", "klippy", "notifications", "power_device", "timelapse",]
