name: Feature request
description: You have a good idea for the bot?
title: "A useful, descriptive title"
labels: ["Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a feature.
  - type: textarea
    id: Suggestion
    attributes:
      label: What would you like to see added?
      description: |
        What would you like to see implemented?
      placeholder: Don't be shy, tell us!
    validations:
      required: true